from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np
from typing import List
import logging


class EmbeddingService:
    def __init__(self, model_name: str = "Qwen/Qwen2-0.5B"):
        """
        Initialize the embedding service with a Qwen model.
        Note: Using a smaller model for efficiency. You can adjust based on your needs.
        """
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.model = AutoModel.from_pretrained(model_name)
        self.model.eval()  # Set to evaluation mode

        # Move model to GPU if available
        if torch.cuda.is_available():
            self.model = self.model.cuda()
            logging.info("Using GPU for embeddings")
        else:
            logging.info("Using CPU for embeddings")

    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text.
        """
        # Tokenize the input text
        inputs = self.tokenizer(
            text,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=512  # Adjust based on your needs
        )

        # Move inputs to the same device as the model
        device = next(self.model.parameters()).device
        inputs = {k: v.to(device) for k, v in inputs.items()}

        # Generate embeddings
        with torch.no_grad():
            outputs = self.model(**inputs)

        # Use the mean of the last hidden states as the embedding
        embeddings = outputs.last_hidden_state.mean(dim=1).cpu().numpy()

        # Convert to list and return
        return embeddings[0].tolist()

    def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for multiple texts.
        """
        embeddings = []
        for text in texts:
            embedding = self.generate_embedding(text)
            embeddings.append(embedding)
        return embeddings

    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of the embeddings generated by this model.
        """
        # Create a simple test embedding to determine the dimension
        test_embedding = self.generate_embedding("test")
        return len(test_embedding)


# Alternative implementation using sentence-transformers for better performance
class SentenceTransformerEmbeddingService:
    def __init__(self, model_name: str = "sentence-transformers/all-MiniLM-L6-v2"):
        """
        Initialize the embedding service using sentence-transformers.
        This is more efficient for embedding generation.
        """
        try:
            from sentence_transformers import SentenceTransformer
            self.model = SentenceTransformer(model_name)
        except ImportError:
            raise ImportError(
                "sentence-transformers is not installed. "
                "Install it with: pip install sentence-transformers"
            )

    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text.
        """
        embedding = self.model.encode([text])
        return embedding[0].tolist()

    def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for multiple texts.
        """
        embeddings = self.model.encode(texts)
        return [embedding.tolist() for embedding in embeddings]

    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of the embeddings generated by this model.
        """
        # Create a simple test embedding to determine the dimension
        test_embedding = self.generate_embedding("test")
        return len(test_embedding)


# Use the sentence transformer implementation as default for better performance
class DefaultEmbeddingService(SentenceTransformerEmbeddingService):
    def __init__(self):
        super().__init__()